### ISSUE TITLE
Back button on SeedKeeper "Select Secret" crashes with AttributeError: 'SeedKeeperSelectView' object has no attribute 'seed'

### ISSUE THREAD

**Issue by afcreamer** [3rdIteration/seedsigner#389]
Hey smee again, I was testing my seedkeeper and found a bug with the back button. I found it in when I have been using the device with my Seedkeeper card to learn the workflows and to get familiar with it.

I used Claude to root cause the issue and below is what it deduced:

---

## Summary

Pressing the back arrow on the "Select Secret" screen, reached via Seeds -> Load a seed -> From SeedKeeper, raises:

```
'SeedKeeperSelectView' object has no attribute 'seed'
```

Back is a normal navigation action on a screen that is explicitly rendered with `show_back_button=True`, so this is reachable in ordinary use with no unusual configuration.

## Cause

This is a use before assignment ordering problem within a single `run()` method.

`SeedKeeperSelectView` (`src/seedsigner/views/seed_views.py:370`) does assign the attribute, but only at line 595, after a secret has been selected and decoded:

```python
self.seed = self.controller.storage.get_pending_seed()
```

The class defines no `__init__`, and the base `View.__init__` sets `controller`, `settings`, `renderer`, canvas dimensions, `screen`, `_redirect` and `is_screensaver_allowed`, but not `seed`. So until line 595 runs, the attribute does not exist at all.

The back-button path sits at line 483, well before that assignment, and returns without ever reaching it:

```python
if selected_menu_num == RET_CODE__BACK_BUTTON:
    if isinstance(self.seed, AezeedSeed):
        return Destination(SeedAezeedPassphraseModeView)
    return Destination(BackStackView)
```

The attribute never exists, so the `isinstance()` check raises before the fallthrough to `BackStackView` can run.

Note that the Aezeed guard is on the unconditional back-button path. It is not gated on the Aezeed setting, so the crash occurs regardless of whether Aezeed support is enabled.

## Impact

Confirmed by testing: with secrets present in the list, selecting Seeds -> Load a seed -> From SeedKeeper and then pressing back crashes rather than returning to the previous screen. There is no way to back out of secret selection.

A second reference to the same missing attribute exists at `src/seedsigner/views/seed_views.py:470`, on the "No Secrets to Load" path:

```python
if len(headers_parsed) < 1:
    self.run_screen(WarningScreen, title="No Secrets to Load", ...)
    if isinstance(self.seed, AezeedSeed):
        return Destination(SeedAezeedPassphraseModeView)
    return Destination(BackStackView)
```

By inspection that should fail identically, which would mean a SeedKeeper containing no loadable secrets also crashes instead of returning cleanly. I have not exercised that path on hardware, so treat it as unverified, but it is the same missing attribute in the same class.

## Steps to reproduce

1. Set up a SeedKeeper card with at least one loadable secret.
2. On the SeedSigner, go to Seeds -> Load a seed -> From SeedKeeper.
3. Enter the card PIN and wait for the "Select Secret" list to populate.
4. Press the back arrow instead of selecting a secret.
5. Observe `'SeedKeeperSelectView' object has no attribute 'seed'`.

## Suggested fix

The minimal change is a safe attribute read at both early sites:

```python
if isinstance(getattr(self, "seed", None), AezeedSeed):
```

Initialising `self.seed = None` in an `__init__` would also work and would make the ordering explicit rather than implicit.

Either way it is worth asking whether the Aezeed branch belongs on these paths at all. Both are reached while the user is still choosing which secret to load, so there is no seed in hand yet by construction, and the check can only ever be false there. If the intent was to return the user to the Aezeed passphrase screen when the SeedKeeper flow was entered from that direction, the entry point needs to be passed into the view explicitly rather than inferred from an attribute that is not populated until line 595.

## Origin

Introduced by #320, "Add Aezeed import support entry toggle and UI flow (off by default)" (commit `5d572bc3`, 2026-03-06), which added the `isinstance(self.seed, AezeedSeed)` checks to this class.

Affected releases are `SeSi-0.8.6+ShSi-B9`, `SeSi-0.8.6+ShSi-B10`, `SeSi-0.8.6+ShSi-B11` and `SeSi-0.8.7+ShSi-B11`. B8 and earlier predate the commit.

Worth noting that the PR is described as off by default, but because the guard sits on the unconditional back-button path, a disabled optional feature breaks a default navigation action for all users.
